# -*- coding: utf-8 -*-
"""ACSC project(matplotlib).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14jcC0KjOo5M1jK1o31jmVEiaI0ZPrJb5
"""

import pandas as pd

import matplotlib.pyplot as plt

df_EnergySource = pd.read_csv ('energy sources_ simple .csv')

print(df_EnergySource)

import numpy as np
Solar = df_EnergySource['Solar']
solar_list = list(Solar)
Coal = df_EnergySource['Coal']
coal_list = list(Coal)
print(solar_list)
print(coal_list)

np.corrcoef(Solar, Coal)

Year = df_EnergySource['Year ']
NaturalGas = df_EnergySource['NaturalGas']
plt.plot(Year, Coal, color = 'magenta', label='Coal')
plt.plot(Year, Solar, color = 'aqua', label='Solar')
plt.plot(Year, NaturalGas, color = 'green', )
plt.title ('Annual Electric Power Generated')
plt.xlabel('Year')
plt.ylabel('In 1,000,000 MWh')
plt.legend (loc="upper right")

df_energypercent = pd.read_csv ('energy sources 07-20 .csv')
print (df_energypercent)

p_solar = df_energypercent['Percent Solar ']
p_coal = df_energypercent['Percent Coal ']
p_naturalgas = df_energypercent['Percent Natural Gas']
p_year = df_energypercent['Year']
print (p_naturalgas)

plt.plot(p_year, p_solar, color = 'blue')
plt.plot(p_year, p_coal, color = 'red')
plt.plot(p_year, p_naturalgas, color = 'black')

df_pop = pd.read_csv ('/content/nv population 10-20.csv')
print(df_pop)

df_pop.plot.bar(x='Year', y='Total population')

